# This is fly.toml file I use to run main.rapidforge.io
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'rapidforge'
primary_region = 'lhr'

[deploy]
wait_timeout = "10m"

[env]
  RF_PORT = ":8080"
  RF_DOMAIN = "main.rapidforge.io"
  RF_DATABASE_URL = "/data/rapidforge.sqlite3"
  RF_KV_URL = "/data/rapidforgekv.sqlite3"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "rapidforge_data"
  destination = "/data"
